---
- name: Install aws-cli and nginx
  ansible.builtin.apt:
    pkg: "{{ apt_packages }}"
    state: present
    update_cache: true

# boto3 is required to run download file from s3
- name: Install boto3
  ansible.builtin.pip:
    name: "{{ python_packages }}"

- name: Download file from s3
  amazon.aws.s3_object:
    bucket: "{{ vars.bucket_name }}"
    mode: get
    dest: "{{ server_code_file_dir }}/{{ code_file }}"
    object: "{{ code_file }}"
    overwrite: true
    region: "{{ bucket_region }}"

- name: Remove default Nginx config file
  ansible.builtin.file:
    path: "{{ nginx_sites_enabled_dir }}/default"
    state: absent

- name: Upload Nginx config file
  ansible.builtin.template:
    src: nginx.j2
    dest: "{{ nginx_sites_available_dir }}/{{ nginx_conf_file }}"

- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ nginx_sites_available_dir }}/{{ nginx_conf_file }}"
    dest: "{{ nginx_sites_enabled_dir }}/{{ nginx_conf_file }}"
    state: link
  notify: Restart nginx