---
- name: Install aws-cli and nginx
  ansible.builtin.apt:
    pkg:
     - nginx
     - awscli
     - python3-pip
    state: present
    update_cache: true

# boto3 is required to run download file from s3
- name: Install boto3
  ansible.builtin.pip:
    name: boto3

- name: Download file from s3
  amazon.aws.s3_object:
    bucket: "{{ vars.bucket_name }}"
    mode: get
    dest: /var/www/html/index.html
    object: index.html
    overwrite: true

# Copy template file to nginx and register its restart handler
- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

