---
- name: Install aws-cli and nginx
  ansible.builtin.apt:
    pkg:
     - nginx
     - awscli
    state: present
    update_cache: true

# - name: Download file from s3

- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx
