---
- name: Deploy html
  hosts: aws_ec2
  roles:
   - nginx
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 8586-terraform-state
    ansible_become: true
    ansible_become_user: root
    ansible_aws_ssm_timeout: 600
